/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'on-primary': '#3c2f00',
        'on-surface-variant': '#d0c5af',
        'surface-dim': '#131317',
        'primary-fixed': '#ffe088',
        'secondary-fixed': '#f1e3a9',
        'surface-charcoal': '#16161E',
        'on-tertiary-fixed-variant': '#594408',
        'text-muted': '#A5A5B2',
        'secondary-container': '#4f471b',
        'surface-container-low': '#1b1b1f',
        'surface-bright': '#39393d',
        'surface-variant': '#353439',
        background: '#131317',
        'on-tertiary': '#3e2e00',
        'secondary-fixed-dim': '#d4c78f',
        'surface-container': '#1f1f23',
        'primary-container': '#d4af37',
        'on-secondary-fixed': '#211b00',
        'on-error': '#690005',
        'surface-border-gold': '#4A3E20',
        'surface-tint': '#e9c349',
        'surface-container-high': '#2a292e',
        'tertiary-fixed': '#ffdf97',
        'on-tertiary-fixed': '#251a00',
        tertiary: '#eacb84',
        'inverse-surface': '#e4e1e7',
        surface: '#131317',
        'tertiary-fixed-dim': '#e2c37d',
        'on-background': '#e4e1e7',
        'on-tertiary-container': '#574206',
        'surface-elevated': '#1F1F2B',
        'outline-variant': '#4d4635',
        'primary-fixed-dim': '#e9c349',
        'on-primary-fixed-variant': '#574500',
        'on-secondary-container': '#c2b57f',
        error: '#ffb4ab',
        'tertiary-container': '#cdb06b',
        'inverse-on-surface': '#303034',
        'surface-container-highest': '#353439',
        'on-surface': '#e4e1e7',
        'on-primary-container': '#554300',
        'on-secondary': '#383006',
        secondary: '#d4c78f',
        'on-error-container': '#ffdad6',
        'error-container': '#93000a',
        primary: '#f2ca50',
        'crimson-accent': '#821D24',
        'inverse-primary': '#735c00',
        outline: '#99907c',
        'on-primary-fixed': '#241a00',
        'surface-container-lowest': '#0e0e12',
        'text-on-dark': '#F5F5F7',
        'on-secondary-fixed-variant': '#4f471b',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'space-3xl': '4.5rem',
        'gutter-desktop': '2rem',
        'space-2xl': '3rem',
        'space-md': '1rem',
        'space-xl': '2rem',
        'space-sm': '0.75rem',
        'space-2xs': '0.25rem',
        'container-max': '1200px',
        'space-lg': '1.5rem',
        'space-4xl': '6rem',
        'card-inner-pad': '2.5rem',
        'space-xs': '0.5rem',
        'margin-desktop': '4rem',
      },
      fontFamily: {
        'body-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-sm': ['"EB Garamond"', 'serif'],
        'headline-md': ['"EB Garamond"', 'serif'],
        'label-gold': ['"Plus Jakarta Sans"', 'sans-serif'],
        'label-caption': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-lg': ['"EB Garamond"', 'serif'],
        'display-hero': ['"EB Garamond"', 'serif'],
        'title-mantra': ['"EB Garamond"', 'serif'],
        'body-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'display-hero-mobile': ['"EB Garamond"', 'serif'],
        'headline-lg-mobile': ['"EB Garamond"', 'serif'],
      },
      fontSize: {
        'body-lg': ['16px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-sm': ['22px', { lineHeight: '30px', letterSpacing: '0.02em', fontWeight: '500' }],
        'headline-md': ['28px', { lineHeight: '38px', letterSpacing: '0.03em', fontWeight: '500' }],
        'label-gold': ['12px', { lineHeight: '18px', letterSpacing: '0.18em', fontWeight: '600' }],
        'label-caption': ['11px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '400' }],
        'headline-lg': ['40px', { lineHeight: '52px', letterSpacing: '0.05em', fontWeight: '400' }],
        'display-hero': ['56px', { lineHeight: '68px', letterSpacing: '0.08em', fontWeight: '400' }],
        'title-mantra': ['20px', { lineHeight: '34px', letterSpacing: '0.04em', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '24px', fontWeight: '400' }],
        'display-hero-mobile': ['36px', { lineHeight: '46px', letterSpacing: '0.04em', fontWeight: '400' }],
        'headline-lg-mobile': ['28px', { lineHeight: '38px', letterSpacing: '0.03em', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
